apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wasteful-pink-canid
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wasteful-pink-canid 
  name: wasteful-pink-canid
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wasteful-pink-canid 
